---
- hosts: debian11
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Clone docker from git
      ansible.builtin.shell: 
        cmd: git clone https://github.com/klimoffgod/ansible.git
    - name: build docker from git
      ansible.builtin.shell:
        cmd: cd ansible &&  docker build . -t aster18
    - name: run  docker-compose mariadb from dockerhub 
      ansible.builtin.shell:
        cmd: docker-compose up -d
