---
- hosts: debian11
  become: true

  tasks:

    - name: apt update and install requirements
      ansible.builtin.shell:
        cmd: apt update && apt install -y aptitude ca-certificates curl lsb-release net-tools mc apt-transport-https gnupg2 software-properties-common git

    - name: add repo and key and install docker docker-compose
      ansible.builtin.shell:
        cmd: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && aptitude update && aptitude install -y docker-ce docker-ce-cli containerd.io

    - name: Clone docker from git
      ansible.builtin.shell: 
        cmd: git clone https://github.com/klimoffgod/ansible.git

    - name: build docker from git
      ansible.builtin.shell:
        cmd: cd ansible &&  docker build . -t aster18

    - name: run  docker-compose mariadb from dockerhub 
      ansible.builtin.shell:
        cmd: cd ansible && docker-compose up -d
