---
- hosts: debian11
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Clone aster config from git
      ansible.builtin.shell: 
        cmd: docker run  -i --tty --entrypoint /entrypoint.sh ass2
       
