---
- hosts: debian11
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Clone docker from git
      ansible.builtin.shell: 
        cmd: git clone https://github.com/klimoffgod/ansible.git
    - name: build docker from git
      ansible.builtin.shell:
        cmd: docker build . -t aster18
    - name: run docker aster18 from build
      ansible.builtin.shell:
        cmd: docker run -d -t --entrypoint /entrypoint.sh  aster18
    - name: run mariadb from dockerhub
      ansible.builtin.shell:
        cmd: docker run --name mariadb -e ALLOW_EMPTY_PASSWORD=yes bitnami/mariadb:latest
