---
- hosts: debian11
  become: true

  tasks:

    - name: apt update and install requirements
      ansible.builtin.shell:
        cmd: apt update && apt install -y aptitude ca-certificates curl lsb-release net-tools mc apt-transport-https gnupg2 software-properties-common git

    - name: add repo and key and install docker docker-compose
      ansible.builtin.shell:
        cmd: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && aptitude update && aptitude install -y docker  docker-ce docker-ce-cli containerd.io docker-compose 
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: users | adding docker users (for use without sudo)
      user:
        name: god
        append: yes
        groups: docker

    - name: Clone docker from git
      ansible.builtin.shell: 
        cmd: git clone https://github.com/klimoffgod/ansible.git

    - name: build docker from git
      ansible.builtin.shell:
        cmd: cd ansible &&  docker build . -t aster18

    - name: run  docker-compose mariadb from dockerhub 
      ansible.builtin.shell:
        cmd: cd ansible && docker-compose up -d
